# Generated by Django 2.1.3 on 2018-11-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0002_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(default='coisa', max_length=100),
            preserve_default=False,
        ),
    ]
